name: migrate_funds_to_smart_account
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  fuse_wallet_sdk: ^0.1.2
#  fuse_wallet_sdk:
#    git:
#      url: https://github.com/fuseio/fuse_wallet_sdk.git
#      ref: feat/erc-4337
  # path: ^1.8.0
  intl: ^0.18.0
  decimal: ^2.3.2
  collection: ^1.17.0
  dio: ^5.3.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
